In [24]:
import numpy as np

In [25]:
np.__version__

'2.3.1'

In [26]:
# list , array
lst = [1,2,3,4,5]
arr =np.array(lst)

In [27]:
arr

array([1, 2, 3, 4, 5])

In [28]:
array =np.array([1,2,3,4,5,6,7,8])


In [29]:
arr

array([1, 2, 3, 4, 5])

In [30]:
lst = [1,2,3,4,5,6]
print("type of list", type(lst))
arr =np.array(lst)
print("arr")
print("types of array", type(arr))

type of list <class 'list'>
arr
types of array <class 'numpy.ndarray'>


In [31]:
arr =np.array(list(range(1,21)))
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [32]:
arr =np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [33]:
np.zeros((5,20)) # 5 row and 20 column

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [34]:
np.ones((5,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
array =np.linespace(1,10,5)
arr

In [ ]:
# 1d array convert to 2d
arr =np.range(0,30)
arr

In [ ]:
arr.reshape((5,6))

In [ ]:
arr.reshape(10,3)

In [ ]:
arr =np.random.randint(1,5,9)
arr # 1 d

array([1, 1, 3, 4, 3, 3, 2, 3, 2], dtype=int32)

In [40]:
arr =np.random.randint(1,5,(3,3))
arr

array([[1, 4, 4],
       [3, 1, 4],
       [4, 1, 1]], dtype=int32)

In [42]:
arr =np.random.random(10)
arr

array([0.01459926, 0.96585146, 0.59795391, 0.21484761, 0.99370322,
       0.79492337, 0.4487876 , 0.5742392 , 0.76959801, 0.83278762])

In [43]:
arr =np.random.random((5,10))
arr

array([[0.25113267, 0.37996451, 0.48945846, 0.19442567, 0.65116649,
        0.98268728, 0.80725424, 0.78951494, 0.34920415, 0.42203178],
       [0.27961767, 0.50045633, 0.56007391, 0.64104451, 0.26669598,
        0.5546121 , 0.65102985, 0.73924048, 0.65112927, 0.2863826 ],
       [0.62119605, 0.37688979, 0.7912127 , 0.21945646, 0.4322282 ,
        0.0076187 , 0.18591231, 0.58567063, 0.79875197, 0.04270733],
       [0.44303703, 0.26073779, 0.71681783, 0.491153  , 0.24959531,
        0.99258341, 0.28910613, 0.98797845, 0.54686834, 0.63014615],
       [0.6872673 , 0.98720443, 0.36412572, 0.32886244, 0.24727121,
        0.53897298, 0.87367744, 0.75635638, 0.87893966, 0.98627276]])

In [ ]:
arr =np.arrange(60).reshape(12,5)
arr

In [49]:
arr.shape
arr.size
arr.dtype
print("shape of array :-", arr.shape)
print("size of array", arr.size)
print("data type:-", arr.dtype)
print("number of dimension", arr.ndim)

shape of array :- (5, 10)
size of array 50
data type:- float64
number of dimension 2


In [ ]:
arr.flatten() # 2d to 1d

array([0.25113267, 0.37996451, 0.48945846, 0.19442567, 0.65116649,
       0.98268728, 0.80725424, 0.78951494, 0.34920415, 0.42203178,
       0.27961767, 0.50045633, 0.56007391, 0.64104451, 0.26669598,
       0.5546121 , 0.65102985, 0.73924048, 0.65112927, 0.2863826 ,
       0.62119605, 0.37688979, 0.7912127 , 0.21945646, 0.4322282 ,
       0.0076187 , 0.18591231, 0.58567063, 0.79875197, 0.04270733,
       0.44303703, 0.26073779, 0.71681783, 0.491153  , 0.24959531,
       0.99258341, 0.28910613, 0.98797845, 0.54686834, 0.63014615,
       0.6872673 , 0.98720443, 0.36412572, 0.32886244, 0.24727121,
       0.53897298, 0.87367744, 0.75635638, 0.87893966, 0.98627276])

In [ ]:
arr.ravel() # 2d ko 1d ko # task differnce

array([0.25113267, 0.37996451, 0.48945846, 0.19442567, 0.65116649,
       0.98268728, 0.80725424, 0.78951494, 0.34920415, 0.42203178,
       0.27961767, 0.50045633, 0.56007391, 0.64104451, 0.26669598,
       0.5546121 , 0.65102985, 0.73924048, 0.65112927, 0.2863826 ,
       0.62119605, 0.37688979, 0.7912127 , 0.21945646, 0.4322282 ,
       0.0076187 , 0.18591231, 0.58567063, 0.79875197, 0.04270733,
       0.44303703, 0.26073779, 0.71681783, 0.491153  , 0.24959531,
       0.99258341, 0.28910613, 0.98797845, 0.54686834, 0.63014615,
       0.6872673 , 0.98720443, 0.36412572, 0.32886244, 0.24727121,
       0.53897298, 0.87367744, 0.75635638, 0.87893966, 0.98627276])

In [52]:
arr.shape

(5, 10)

In [ ]:
arr.T # convert 5 row 5 column

array([[0.25113267, 0.27961767, 0.62119605, 0.44303703, 0.6872673 ],
       [0.37996451, 0.50045633, 0.37688979, 0.26073779, 0.98720443],
       [0.48945846, 0.56007391, 0.7912127 , 0.71681783, 0.36412572],
       [0.19442567, 0.64104451, 0.21945646, 0.491153  , 0.32886244],
       [0.65116649, 0.26669598, 0.4322282 , 0.24959531, 0.24727121],
       [0.98268728, 0.5546121 , 0.0076187 , 0.99258341, 0.53897298],
       [0.80725424, 0.65102985, 0.18591231, 0.28910613, 0.87367744],
       [0.78951494, 0.73924048, 0.58567063, 0.98797845, 0.75635638],
       [0.34920415, 0.65112927, 0.79875197, 0.54686834, 0.87893966],
       [0.42203178, 0.2863826 , 0.04270733, 0.63014615, 0.98627276]])

In [54]:
arr.T.shape

(10, 5)

In [ ]:
arr =np.arrange(30)

In [ ]:
arr[20]

In [57]:
arr[0:12]

array([[0.25113267, 0.37996451, 0.48945846, 0.19442567, 0.65116649,
        0.98268728, 0.80725424, 0.78951494, 0.34920415, 0.42203178],
       [0.27961767, 0.50045633, 0.56007391, 0.64104451, 0.26669598,
        0.5546121 , 0.65102985, 0.73924048, 0.65112927, 0.2863826 ],
       [0.62119605, 0.37688979, 0.7912127 , 0.21945646, 0.4322282 ,
        0.0076187 , 0.18591231, 0.58567063, 0.79875197, 0.04270733],
       [0.44303703, 0.26073779, 0.71681783, 0.491153  , 0.24959531,
        0.99258341, 0.28910613, 0.98797845, 0.54686834, 0.63014615],
       [0.6872673 , 0.98720443, 0.36412572, 0.32886244, 0.24727121,
        0.53897298, 0.87367744, 0.75635638, 0.87893966, 0.98627276]])

In [59]:
arr 

array([[0.25113267, 0.37996451, 0.48945846, 0.19442567, 0.65116649,
        0.98268728, 0.80725424, 0.78951494, 0.34920415, 0.42203178],
       [0.27961767, 0.50045633, 0.56007391, 0.64104451, 0.26669598,
        0.5546121 , 0.65102985, 0.73924048, 0.65112927, 0.2863826 ],
       [0.62119605, 0.37688979, 0.7912127 , 0.21945646, 0.4322282 ,
        0.0076187 , 0.18591231, 0.58567063, 0.79875197, 0.04270733],
       [0.44303703, 0.26073779, 0.71681783, 0.491153  , 0.24959531,
        0.99258341, 0.28910613, 0.98797845, 0.54686834, 0.63014615],
       [0.6872673 , 0.98720443, 0.36412572, 0.32886244, 0.24727121,
        0.53897298, 0.87367744, 0.75635638, 0.87893966, 0.98627276]])

In [60]:
arr[0]

array([0.25113267, 0.37996451, 0.48945846, 0.19442567, 0.65116649,
       0.98268728, 0.80725424, 0.78951494, 0.34920415, 0.42203178])

In [61]:
arr[0]=100

In [ ]:
arr =np.arrange(60).reshape(12,5)

In [62]:
arr[1,6]

np.float64(0.6510298524393087)

In [67]:
arr[1,3:5]

array([0.64104451, 0.26669598])

In [68]:
arr[0:5,1:2]

array([[100.        ],
       [  0.50045633],
       [  0.37688979],
       [  0.26073779],
       [  0.98720443]])

In [ ]:
arr[1,1] = 100 # replace element
arr

array([[1.00000000e+02, 1.00000000e+02, 1.00000000e+02, 1.00000000e+02,
        1.00000000e+02, 1.00000000e+02, 1.00000000e+02, 1.00000000e+02,
        1.00000000e+02, 1.00000000e+02],
       [2.79617671e-01, 1.00000000e+02, 5.60073908e-01, 6.41044512e-01,
        2.66695978e-01, 5.54612098e-01, 6.51029852e-01, 7.39240481e-01,
        6.51129272e-01, 2.86382600e-01],
       [6.21196046e-01, 3.76889795e-01, 7.91212696e-01, 2.19456461e-01,
        4.32228202e-01, 7.61869788e-03, 1.85912314e-01, 5.85670630e-01,
        7.98751970e-01, 4.27073252e-02],
       [4.43037031e-01, 2.60737791e-01, 7.16817826e-01, 4.91152996e-01,
        2.49595309e-01, 9.92583413e-01, 2.89106129e-01, 9.87978447e-01,
        5.46868339e-01, 6.30146153e-01],
       [6.87267297e-01, 9.87204426e-01, 3.64125717e-01, 3.28862440e-01,
        2.47271213e-01, 5.38972975e-01, 8.73677438e-01, 7.56356384e-01,
        8.78939659e-01, 9.86272764e-01]])

In [71]:
arr[11:4]

array([], shape=(0, 10), dtype=float64)

In [72]:
arr[-1]

array([0.6872673 , 0.98720443, 0.36412572, 0.32886244, 0.24727121,
       0.53897298, 0.87367744, 0.75635638, 0.87893966, 0.98627276])

In [73]:
arr[-1][-1]

np.float64(0.986272763961021)

In [ ]:
arr =np.array(np.arrange(225).reshape(5,15,3))

In [ ]:
arr.ndim,arr.shape, arr.size, dtype('float32')

In [ ]:
arr[0] # table dekhna

array([100., 100., 100., 100., 100., 100., 100., 100., 100., 100.])

In [77]:
arr[2]

array([0.62119605, 0.37688979, 0.7912127 , 0.21945646, 0.4322282 ,
       0.0076187 , 0.18591231, 0.58567063, 0.79875197, 0.04270733])

In [ ]:
arr[0,2:2]

In [80]:
arr[0,3:5]

array([100., 100.])

In [ ]:
arr[:,0,:]

In [ ]:
arr[:,0,0:1,0:1]

In [ ]:
arr[0,1,1] = 1000

In [84]:
arr

array([[1.00000000e+02, 1.00000000e+02, 1.00000000e+02, 1.00000000e+02,
        1.00000000e+02, 1.00000000e+02, 1.00000000e+02, 1.00000000e+02,
        1.00000000e+02, 1.00000000e+02],
       [2.79617671e-01, 1.00000000e+02, 5.60073908e-01, 6.41044512e-01,
        2.66695978e-01, 5.54612098e-01, 6.51029852e-01, 7.39240481e-01,
        6.51129272e-01, 2.86382600e-01],
       [6.21196046e-01, 3.76889795e-01, 7.91212696e-01, 2.19456461e-01,
        4.32228202e-01, 7.61869788e-03, 1.85912314e-01, 5.85670630e-01,
        7.98751970e-01, 4.27073252e-02],
       [4.43037031e-01, 2.60737791e-01, 7.16817826e-01, 4.91152996e-01,
        2.49595309e-01, 9.92583413e-01, 2.89106129e-01, 9.87978447e-01,
        5.46868339e-01, 6.30146153e-01],
       [6.87267297e-01, 9.87204426e-01, 3.64125717e-01, 3.28862440e-01,
        2.47271213e-01, 5.38972975e-01, 8.73677438e-01, 7.56356384e-01,
        8.78939659e-01, 9.86272764e-01]])

In [85]:
arr =np.array([1,3,4,5,6])

In [86]:
arr

array([1, 3, 4, 5, 6])

In [90]:
arr+2

array([3, 5, 6, 7, 8])

In [89]:
arr-2

array([-1,  1,  2,  3,  4])

In [88]:
arr*2

array([ 2,  6,  8, 10, 12])

In [87]:
arr/2

array([0.5, 1.5, 2. , 2.5, 3. ])

In [91]:
arr1 = np.array([1,2,3,4,5,6,7])
arr2 = np.array([1,2,6,7,8])

In [ ]:
arr1-arr2

In [ ]:
git clone 
git  add .
git comit - "comit"
push 
status